### Задание 1

#### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
y = -np.sort(-x)
print(y)

[9 8 7 6 5 4 3 2 1 0]


### Задание 2

#### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
z = np.diag(np.array(y),k=0)
z

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
np.sum(z)

45

### Задание 3

#### Решите систему уравнений: 
    4x + 2y + z = 4 
    x + 3y = 12 
    5y + 4z = -3



In [5]:
from numpy import linalg

a = np.array( [ [4, 2,0], [1, 3, 0],[0,5,4] ] )
b = np.array( [4, 12, -3] )

linalg.solve(a, b)

array([-1.2 ,  4.4 , -6.25])

#### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [6]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [7]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [8]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [35]:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
user_id = 1

user_results = {}

for i in users_stats:
    
    x = cosine(i,next_user_stats)
    user_results[user_id] = round(x,4)
    #print(f'Сходство с пользователем {user_id} составляет {round(x,4)}')
    user_id+=1

max_val = max(user_results.values())

for k in user_results.items():
    if k[1] == max_val:
        print(f'Наибольшее сходство нового пользователя с пользвателем {k[0]}')
    

Наибольшее сходство нового пользователя с пользвателем 8
